/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Q2;

import Q1.Ponto;
import Q1.Quadrante;

/**
 *
 * @author molle
 */
public class Tela extends javax.swing.JFrame {

    /**
     * Creates new form Tela
     */
    public Tela() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTEixoX = new javax.swing.JTextField();
        jTEixoY = new javax.swing.JTextField();
        jBAvaliar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jCIncideSobreX = new javax.swing.JCheckBox();
        jCIncideSobreY = new javax.swing.JCheckBox();
        jCIncideSegundo = new javax.swing.JCheckBox();
        jCIncidePrimeiro = new javax.swing.JCheckBox();
        jCIncideTerceiro = new javax.swing.JCheckBox();
        jCIncideQuarto = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Ponto");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("Eixo X:");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setText("Posição:");

        jTEixoX.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N

        jTEixoY.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jTEixoY.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTEixoYActionPerformed(evt);
            }
        });

        jBAvaliar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jBAvaliar.setText("Avaliar");
        jBAvaliar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBAvaliarActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setText("Eixo Y:");

        jCIncideSobreX.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jCIncideSobreX.setText("Incide sobre o Eixo X");
        jCIncideSobreX.setEnabled(false);

        jCIncideSobreY.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jCIncideSobreY.setText("Incide sobre o Eixo Y");
        jCIncideSobreY.setEnabled(false);

        jCIncideSegundo.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jCIncideSegundo.setText("No 2º Quadrante");
        jCIncideSegundo.setEnabled(false);

        jCIncidePrimeiro.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jCIncidePrimeiro.setText("No 1º Quadrante");
        jCIncidePrimeiro.setEnabled(false);

        jCIncideTerceiro.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jCIncideTerceiro.setText("No 3º Quadrante");
        jCIncideTerceiro.setEnabled(false);
        jCIncideTerceiro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCIncideTerceiroActionPerformed(evt);
            }
        });

        jCIncideQuarto.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jCIncideQuarto.setText("No 4º Quadrante");
        jCIncideQuarto.setEnabled(false);
        jCIncideQuarto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCIncideQuartoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jBAvaliar)
                .addGap(149, 149, 149))
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(44, 44, 44)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTEixoX)
                            .addComponent(jTEixoY, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(239, 239, 239))))
            .addGroup(layout.createSequentialGroup()
                .addGap(79, 79, 79)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jCIncideQuarto)
                    .addComponent(jCIncideTerceiro)
                    .addComponent(jCIncidePrimeiro)
                    .addComponent(jCIncideSegundo)
                    .addComponent(jCIncideSobreY)
                    .addComponent(jCIncideSobreX))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jTEixoX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addComponent(jBAvaliar)
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTEixoY, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(59, 59, 59)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jCIncideSobreX)
                .addGap(18, 18, 18)
                .addComponent(jCIncideSobreY)
                .addGap(18, 18, 18)
                .addComponent(jCIncidePrimeiro)
                .addGap(18, 18, 18)
                .addComponent(jCIncideSegundo)
                .addGap(18, 18, 18)
                .addComponent(jCIncideTerceiro)
                .addGap(18, 18, 18)
                .addComponent(jCIncideQuarto)
                .addContainerGap(76, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jCIncideTerceiroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCIncideTerceiroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCIncideTerceiroActionPerformed

    private void jCIncideQuartoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCIncideQuartoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCIncideQuartoActionPerformed

    private void jTEixoYActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTEixoYActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTEixoYActionPerformed

    private void jBAvaliarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBAvaliarActionPerformed
        Limpar();
        Ponto p = new Ponto(Integer.parseInt(jTEixoX.getText()), Integer.parseInt(jTEixoY.getText()));

        Quadrante q = p.identificarQuadrante();

        switch (q) {
            case Quadrante.PRIMEIRO:
                jCIncidePrimeiro.setSelected(true);
                break;
            case Quadrante.SEGUNDO:
                jCIncideSegundo.setSelected(true);
                break;
            case Quadrante.TERCEIRO:
                jCIncideTerceiro.setSelected(true);
                break;
            case Quadrante.QUARTO:
                jCIncideQuarto.setSelected(true);
                break;
            case Quadrante.NENHUM:
                if (p.estaIncindindoSobreX()) {
                    jCIncideSobreX.setSelected(true);
                }
                if (p.estaIncindindoSobreY()) {
                    jCIncideSobreY.setSelected(true);
                }
                break;
        }
    }//GEN-LAST:event_jBAvaliarActionPerformed

    private void Limpar() {
        jCIncideSobreX.setSelected(false);
        jCIncideSobreY.setSelected(false);
        jCIncidePrimeiro.setSelected(false);
        jCIncideSegundo.setSelected(false);
        jCIncideTerceiro.setSelected(false);
        jCIncideQuarto.setSelected(false);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tela().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBAvaliar;
    private javax.swing.JCheckBox jCIncidePrimeiro;
    private javax.swing.JCheckBox jCIncideQuarto;
    private javax.swing.JCheckBox jCIncideSegundo;
    private javax.swing.JCheckBox jCIncideSobreX;
    private javax.swing.JCheckBox jCIncideSobreY;
    private javax.swing.JCheckBox jCIncideTerceiro;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField jTEixoX;
    private javax.swing.JTextField jTEixoY;
    // End of variables declaration//GEN-END:variables
}
